<script setup>

import { ref } from 'vue'

const selectedMonth = ref('2026-08')

const reports = ref([
    {
        name: 'Employee Attendance Report',
        description: 'View employee attendance details',
        type: 'Attendance'
    },
    {
        name: 'Employee List Report',
        description: 'View complete employee information',
        type: 'Employee'
    },
    {
        name: 'Leave Report',
        description: 'View employee leave information',
        type: 'Leave'
    },
    {
        name: 'Salary Report',
        description: 'View employee salary information',
        type: 'Salary'
    }
])

</script>


<template>

<div class="reports-page">

    <div class="page-header">

        <div>

            <h2>
                Reports
            </h2>

            <p>
                Generate and view HRMS reports
            </p>

        </div>

    </div>


    <div class="filter-section">

        <div class="field">

            <label>
                Month
            </label>

            <input
                v-model="selectedMonth"
                type="month"
            />

        </div>


        <div class="field">

            <label>
                Report Type
            </label>

            <select>

                <option value="">
                    All Reports
                </option>

                <option>
                    Attendance
                </option>

                <option>
                    Employee
                </option>

                <option>
                    Leave
                </option>

                <option>
                    Salary
                </option>

            </select>

        </div>


        <button class="generate-button">
            Generate Report
        </button>

    </div>


    <div class="report-section">

        <h3>
            Available Reports
        </h3>


        <div class="report-grid">


            <div
                v-for="report in reports"
                :key="report.name"
                class="report-card"
            >

                <div class="report-icon">

                    <i class="bi bi-file-earmark-text"></i>

                </div>


                <div class="report-content">

                    <h4>
                        {{ report.name }}
                    </h4>

                    <p>
                        {{ report.description }}
                    </p>

                    <span>
                        {{ report.type }}
                    </span>

                </div>


                <button class="view-button">
                    View
                </button>

            </div>


        </div>

    </div>


    <div class="report-section">

        <h3>
            Recent Reports
        </h3>


        <div class="report-table">

            <table>

                <thead>

                    <tr>

                        <th>
                            Report Name
                        </th>

                        <th>
                            Type
                        </th>

                        <th>
                            Generated Date
                        </th>

                        <th>
                            Generated By
                        </th>

                        <th>
                            Action
                        </th>

                    </tr>

                </thead>


                <tbody>

                    <tr>

                        <td>
                            August Attendance Report
                        </td>

                        <td>
                            Attendance
                        </td>

                        <td>
                            12-08-2026
                        </td>

                        <td>
                            Admin
                        </td>

                        <td>

                            <button class="view-button">
                                View
                            </button>

                        </td>

                    </tr>


                    <tr>

                        <td>
                            Employee List Report
                        </td>

                        <td>
                            Employee
                        </td>

                        <td>
                            10-08-2026
                        </td>

                        <td>
                            Admin
                        </td>

                        <td>

                            <button class="view-button">
                                View
                            </button>

                        </td>

                    </tr>


                </tbody>

            </table>

        </div>

    </div>

</div>

</template>


<style scoped>

.reports-page {

    padding: 20px;

}


.page-header {

    margin-bottom: 20px;

}


.page-header h2 {

    margin: 0;

    font-size: 20px;

}


.page-header p {

    margin: 5px 0 0;

    color: #777;

    font-size: 13px;

}


.filter-section {

    display: flex;

    align-items: flex-end;

    gap: 15px;

    background: white;

    border: 1px solid #d0d5db;

    padding: 18px;

    margin-bottom: 20px;

}


.field {

    display: flex;

    flex-direction: column;

    gap: 6px;

}


.field label {

    font-size: 12px;

    font-weight: bold;

}


.field input,
.field select {

    padding: 9px;

    min-width: 180px;

    border: 1px solid #ccc;

    border-radius: 4px;

}


.generate-button {

    padding: 9px 18px;

    background: #354a68;

    color: white;

    border: none;

    border-radius: 4px;

    cursor: pointer;

}


.report-section {

    background: white;

    border: 1px solid #d0d5db;

    padding: 20px;

    margin-bottom: 20px;

}


.report-section h3 {

    margin-top: 0;

}


.report-grid {

    display: grid;

    grid-template-columns: repeat(2, 1fr);

    gap: 15px;

}


.report-card {

    display: flex;

    align-items: center;

    gap: 15px;

    border: 1px solid #ddd;

    padding: 15px;

    border-radius: 5px;

}


.report-icon {

    width: 42px;

    height: 42px;

    display: flex;

    align-items: center;

    justify-content: center;

    background: #f0f2f5;

    border-radius: 5px;

    font-size: 20px;

}


.report-content {

    flex: 1;

}


.report-content h4 {

    margin: 0 0 5px;

}


.report-content p {

    margin: 0 0 7px;

    color: #777;

    font-size: 12px;

}


.report-content span {

    font-size: 11px;

    color: #555;

}


.view-button {

    padding: 6px 12px;

    background: white;

    color: #354a68;

    border: 1px solid #354a68;

    border-radius: 4px;

    cursor: pointer;

}


.report-table {

    overflow-x: auto;

}


table {

    width: 100%;

    border-collapse: collapse;

}


th {

    padding: 12px;

    text-align: left;

    background: #f2f4f7;

    font-size: 13px;

}


td {

    padding: 12px;

    border-top: 1px solid #e5e5e5;

    font-size: 13px;

}


@media (max-width: 800px) {

    .filter-section {

        flex-wrap: wrap;

    }


    .report-grid {

        grid-template-columns: 1fr;

    }

}

</style>